# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('uniprot_accession', models.CharField(blank=True, max_length=200, null=True)),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('protein_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('keggid', models.CharField(blank=True, max_length=200, null=True)),
                ('kegg_url', models.URLField(blank=True, null=True)),
                ('chemblid', models.CharField(blank=True, max_length=200, null=True)),
                ('chembl_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('pdbid', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
