# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0002_auto_20180109_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pchembl_value', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_value', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_type', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_units', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_id', models.IntegerField(blank=True, null=True)),
                ('assay_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chembl_id_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('assay_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBL_small_molecule_all_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_chembl_id', models.CharField(blank=True, max_length=200, null=True)),
                ('molecule_chembl_id_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('molecule_smile', models.CharField(blank=True, max_length=2048, null=True)),
                ('activity_pchembl_value', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_standard_value', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_standard_type', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_standard_units', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_doc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_assay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assay_chembl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assay_chembl_id_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('assay_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('assay_assay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_chembl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_chembl_id_url', models.URLField(blank=True, null=True)),
                ('doc_doi', models.CharField(blank=True, max_length=200, null=True)),
                ('docs_title', models.CharField(blank=True, max_length=1024, null=True)),
                ('doc_pubmed_id', models.CharField(blank=True, max_length=50, null=True)),
                ('doc_pubmed_id_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChEMBLSmallMolecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chembl_url', models.URLField(blank=True, null=True)),
                ('canonical_smiles', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('doi', models.CharField(blank=True, max_length=1024, null=True)),
                ('pubmed_id', models.IntegerField(blank=True, null=True)),
                ('pubmed_id_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('chembl_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chembl_id_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='compounds.Activity')),
                ('small_molecule_chembls', models.ManyToManyField(blank=True, to='compounds.ChEMBLSmallMolecule')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('drug_state', models.CharField(blank=True, max_length=1024, null=True)),
                ('cas', models.CharField(blank=True, max_length=1024, null=True)),
                ('IUPAC', models.CharField(blank=True, max_length=2048, null=True)),
                ('drugbank_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('drugbank_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('cid', models.CharField(blank=True, max_length=200, null=True)),
                ('first_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('smiles', models.CharField(blank=True, max_length=2048, null=True)),
                ('formula', models.CharField(blank=True, max_length=1024, null=True)),
                ('mol', django_rdkit.models.fields.MolField(blank=True, null=True)),
                ('mol_block', models.TextField(blank=True)),
                ('bfp', django_rdkit.models.fields.BfpField(blank=True, null=True)),
                ('mol_file', models.FileField(blank=True, null=True, upload_to='mol_files')),
                ('mol_image', models.ImageField(blank=True, null=True, upload_to='mol_images')),
                ('mol_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('alogp', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Calculated AlogP')),
                ('hba', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of hydrogen bond acceptor')),
                ('hbd', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of hydrogen bond donor')),
                ('psa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Polar surface area')),
                ('rtb', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of rotatable bonds')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
                ('descripor', models.CharField(blank=True, max_length=2048, null=True)),
                ('drugs', models.ManyToManyField(blank=True, to='compounds.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(blank=True, max_length=200, null=True)),
                ('uniprot_accession', models.CharField(blank=True, max_length=200, null=True)),
                ('gene', models.CharField(blank=True, max_length=200, null=True)),
                ('protein_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('keggid', models.CharField(blank=True, max_length=200, null=True)),
                ('kegg_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('chemblid', models.CharField(blank=True, max_length=200, null=True)),
                ('chembl_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('type', models.CharField(blank=True, max_length=2048, null=True)),
                ('pdbid', models.CharField(blank=True, max_length=4096, null=True)),
                ('chembl_small_molecules', models.ManyToManyField(blank=True, to='compounds.ChEMBLSmallMolecule')),
                ('drugbankids', models.ManyToManyField(blank=True, to='compounds.DrugBankID')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='targets',
            field=models.ManyToManyField(blank=True, to='compounds.Target'),
        ),
        migrations.AddField(
            model_name='drug',
            name='targets',
            field=models.ManyToManyField(blank=True, to='compounds.Target'),
        ),
        migrations.AddField(
            model_name='assay',
            name='chembl_small_molecules',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBLSmallMolecule'),
        ),
        migrations.AddField(
            model_name='activity',
            name='small_molecule_chembl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBLSmallMolecule'),
        ),
    ]
