# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_auto_20180109_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='chembl_small_molecules_all_infos',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBL_small_molecule_all_info'),
        ),
    ]
