# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0004_target_chembl_small_molecules_all_infos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='small_molecule_chembl',
        ),
        migrations.RemoveField(
            model_name='assay',
            name='chembl_small_molecules',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='small_molecule_chembls',
        ),
        migrations.RemoveField(
            model_name='target',
            name='chembl_small_molecules',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Assay',
        ),
        migrations.DeleteModel(
            name='ChEMBLSmallMolecule',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
